// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebsiteBanXeMay.Data;

#nullable disable

namespace WebsiteBanXeMay.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebsiteBanXeMay.Models.ChucVu", b =>
                {
                    b.Property<int>("MaChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChucVu"));

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaChucVu");

                    b.ToTable("ChucVu", (string)null);

                    b.HasData(
                        new
                        {
                            MaChucVu = 1,
                            TenChucVu = "Admin"
                        },
                        new
                        {
                            MaChucVu = 2,
                            TenChucVu = "Nhân viên"
                        },
                        new
                        {
                            MaChucVu = 3,
                            TenChucVu = "Khách hàng"
                        });
                });

            modelBuilder.Entity("WebsiteBanXeMay.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDanhMuc");

                    b.ToTable("DanhMuc", (string)null);

                    b.HasData(
                        new
                        {
                            MaDanhMuc = 1,
                            TenDanhMuc = "Xe số"
                        },
                        new
                        {
                            MaDanhMuc = 2,
                            TenDanhMuc = "Xe ga"
                        },
                        new
                        {
                            MaDanhMuc = 3,
                            TenDanhMuc = "Xe thể thao"
                        },
                        new
                        {
                            MaDanhMuc = 4,
                            TenDanhMuc = "Xe điện"
                        });
                });

            modelBuilder.Entity("WebsiteBanXeMay.Models.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSanPham"));

                    b.Property<int?>("DanhMucMaDanhMuc")
                        .HasColumnType("int");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaSanPham");

                    b.HasIndex("DanhMucMaDanhMuc");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("TrangThai");

                    b.ToTable("SanPham", (string)null);

                    b.HasData(
                        new
                        {
                            MaSanPham = 1,
                            Gia = 17900000m,
                            HinhAnh = "wave-alpha.jpg",
                            MaDanhMuc = 1,
                            MoTa = "Xe số phổ thông tiết kiệm nhiên liệu",
                            SoLuongTon = 50,
                            TenSanPham = "Honda Wave Alpha 110",
                            TrangThai = true
                        },
                        new
                        {
                            MaSanPham = 2,
                            Gia = 32900000m,
                            HinhAnh = "airblade.jpg",
                            MaDanhMuc = 2,
                            MoTa = "Xe ga thời trang, vận hành êm ái",
                            SoLuongTon = 30,
                            TenSanPham = "Honda Air Blade 125",
                            TrangThai = true
                        },
                        new
                        {
                            MaSanPham = 3,
                            Gia = 48900000m,
                            HinhAnh = "exciter.jpg",
                            MaDanhMuc = 1,
                            MoTa = "Xe côn tay thể thao mạnh mẽ",
                            SoLuongTon = 20,
                            TenSanPham = "Yamaha Exciter 155",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("WebsiteBanXeMay.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaChucVu")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("MaChucVu");

                    b.ToTable("TaiKhoan", (string)null);

                    b.HasData(
                        new
                        {
                            MaTaiKhoan = 1,
                            DiaChi = "An Giang",
                            HoTen = "Quản Trị Viên",
                            MaChucVu = 1,
                            MatKhau = "jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=",
                            SoDienThoai = "0901234567",
                            TenDangNhap = "admin",
                            TrangThai = true
                        },
                        new
                        {
                            MaTaiKhoan = 2,
                            DiaChi = "An Giang",
                            HoTen = "Nhân Viên Bán Hàng",
                            MaChucVu = 2,
                            MatKhau = "jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=",
                            SoDienThoai = "0987654321",
                            TenDangNhap = "nhanvien",
                            TrangThai = true
                        },
                        new
                        {
                            MaTaiKhoan = 3,
                            DiaChi = "An Giang",
                            HoTen = "Khách Hàng Test",
                            MaChucVu = 3,
                            MatKhau = "jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=",
                            SoDienThoai = "0912345678",
                            TenDangNhap = "khachhang",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("WebsiteBanXeMay.Models.SanPham", b =>
                {
                    b.HasOne("WebsiteBanXeMay.Models.DanhMuc", null)
                        .WithMany("SanPhams")
                        .HasForeignKey("DanhMucMaDanhMuc");

                    b.HasOne("WebsiteBanXeMay.Models.DanhMuc", "DanhMuc")
                        .WithMany()
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_SanPham_DanhMuc");

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("WebsiteBanXeMay.Models.TaiKhoan", b =>
                {
                    b.HasOne("WebsiteBanXeMay.Models.ChucVu", "ChucVu")
                        .WithMany()
                        .HasForeignKey("MaChucVu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TaiKhoan_ChucVu");

                    b.Navigation("ChucVu");
                });

            modelBuilder.Entity("WebsiteBanXeMay.Models.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
